### ISSUE TITLE
Nice tooltips for Boost-based themes

### ISSUE THREAD

**Issue by Vyacheslav-GrebenyukNURE** [moodle-an-hochschulen/moodle-local_navbarplus#8]
Please add to line 130 two attributes for support tooltips in Boost-based themes
      $linkattributes = array('alt' => $itemtitle, 'title' => $itemtitle, 'data-tooltip' => 'tooltip', 'data-placement' => 'bottom');

**Comment by Kathrin84** [comment]
Hi @Vyacheslav-GrebenyukNURE,

thank you very much for your proposal to improve the tooltips and I'm sorry, that I come back to you this late (due resources challenges).

First I can say that your proposal won't work that way, because Bootstrap would require a `data-toggle="tooltip"`.
Unfortunately, this Boostrap core framework is not used in Moodle currently and it would be a higher effort to get this working and, more important, to get this unified with the core icons that do not use the tooltips currently. Furthermore, we're not convinced that the usage on mobile devices would benefit from the tooltips. 

So I will close this issue with the flag "won't do". 
If Moodle core would add the tooltip functionality to their icons, we will adapt it for the navbarplus icons, of course.

Thank you for your understanding!

Best, Kathrin
